import { BlackjackAction } from "../types/Action";
import { Hand } from "../types/Card";

const actionMap: {[p: string]: {[d: string] : BlackjackAction}} = {
  // Hard hands 5-19
  "5": {
    "2": BlackjackAction.HIT,
    "3": BlackjackAction.HIT,
    "4": BlackjackAction.HIT,
    "5": BlackjackAction.HIT,
    "6": BlackjackAction.HIT,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    T: BlackjackAction.HIT,
    A: BlackjackAction.HIT,
  },
  "6": {
    "2": BlackjackAction.HIT,
    "3": BlackjackAction.HIT,
    "4": BlackjackAction.HIT,
    "5": BlackjackAction.HIT,
    "6": BlackjackAction.HIT,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    "T": BlackjackAction.HIT,
    "A": BlackjackAction.HIT,
  },
  "7": {
    "2": BlackjackAction.HIT,
    "3": BlackjackAction.HIT,
    "4": BlackjackAction.HIT,
    "5": BlackjackAction.HIT,
    "6": BlackjackAction.HIT,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    "T": BlackjackAction.HIT,
    "A": BlackjackAction.HIT,
  },
  "8": {
    "2": BlackjackAction.HIT,
    "3": BlackjackAction.HIT,
    "4": BlackjackAction.HIT,
    "5": BlackjackAction.HIT,
    "6": BlackjackAction.HIT,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    "T": BlackjackAction.HIT,
    "A": BlackjackAction.HIT,
  },
  "9": {
    "2": BlackjackAction.HIT,
    "3": BlackjackAction.DOUBLE,
    "4": BlackjackAction.DOUBLE,
    "5": BlackjackAction.DOUBLE,
    "6": BlackjackAction.DOUBLE,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    "T": BlackjackAction.HIT,
    "A": BlackjackAction.HIT,
  },
  "10": {
    "2": BlackjackAction.DOUBLE,
    "3": BlackjackAction.DOUBLE,
    "4": BlackjackAction.DOUBLE,
    "5": BlackjackAction.DOUBLE,
    "6": BlackjackAction.DOUBLE,
    "7": BlackjackAction.DOUBLE,
    "8": BlackjackAction.DOUBLE,
    "9": BlackjackAction.DOUBLE,
    "T": BlackjackAction.HIT,
    "A": BlackjackAction.HIT,
  },
  "11": {
    "2": BlackjackAction.DOUBLE,
    "3": BlackjackAction.DOUBLE,
    "4": BlackjackAction.DOUBLE,
    "5": BlackjackAction.DOUBLE,
    "6": BlackjackAction.DOUBLE,
    "7": BlackjackAction.DOUBLE,
    "8": BlackjackAction.DOUBLE,
    "9": BlackjackAction.DOUBLE,
    "T": BlackjackAction.DOUBLE,
    "A": BlackjackAction.DOUBLE,
  },
  "12": {
    "2": BlackjackAction.HIT,
    "3": BlackjackAction.HIT,
    "4": BlackjackAction.STAND,
    "5": BlackjackAction.STAND,
    "6": BlackjackAction.STAND,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    "T": BlackjackAction.HIT,
    "A": BlackjackAction.HIT,
  },
  "13": {
    "2": BlackjackAction.STAND,
    "3": BlackjackAction.STAND,
    "4": BlackjackAction.STAND,
    "5": BlackjackAction.STAND,
    "6": BlackjackAction.STAND,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    T: BlackjackAction.HIT,
    A: BlackjackAction.HIT,
  },
  "14": {
    "2": BlackjackAction.STAND,
    "3": BlackjackAction.STAND,
    "4": BlackjackAction.STAND,
    "5": BlackjackAction.STAND,
    "6": BlackjackAction.STAND,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    T: BlackjackAction.HIT,
    A: BlackjackAction.HIT,
  },
  "15": {
    "2": BlackjackAction.STAND,
    "3": BlackjackAction.STAND,
    "4": BlackjackAction.STAND,
    "5": BlackjackAction.STAND,
    "6": BlackjackAction.STAND,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    "T": BlackjackAction.HIT,
    "A": BlackjackAction.HIT,
  },
  "16": {
    "2": BlackjackAction.STAND,
    "3": BlackjackAction.STAND,
    "4": BlackjackAction.STAND,
    "5": BlackjackAction.STAND,
    "6": BlackjackAction.STAND,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    "T": BlackjackAction.HIT,
    "A": BlackjackAction.HIT,
  },
  "17": {
    "2": BlackjackAction.STAND,
    "3": BlackjackAction.STAND,
    "4": BlackjackAction.STAND,
    "5": BlackjackAction.STAND,
    "6": BlackjackAction.STAND,
    "7": BlackjackAction.STAND,
    "8": BlackjackAction.STAND,
    "9": BlackjackAction.STAND,
    "T": BlackjackAction.STAND,
    "A": BlackjackAction.STAND,
  },
  "18": {
    "2": BlackjackAction.STAND,
    "3": BlackjackAction.STAND,
    "4": BlackjackAction.STAND,
    "5": BlackjackAction.STAND,
    "6": BlackjackAction.STAND,
    "7": BlackjackAction.STAND,
    "8": BlackjackAction.STAND,
    "9": BlackjackAction.STAND,
    "T": BlackjackAction.STAND,
    "A": BlackjackAction.STAND,
  },
  "19": {
    "2": BlackjackAction.STAND,
    "3": BlackjackAction.STAND,
    "4": BlackjackAction.STAND,
    "5": BlackjackAction.STAND,
    "6": BlackjackAction.STAND,
    "7": BlackjackAction.STAND,
    "8": BlackjackAction.STAND,
    "9": BlackjackAction.STAND,
    "T": BlackjackAction.STAND,
    "A": BlackjackAction.STAND,
  },
  "20": {
    "2": BlackjackAction.STAND,
    "3": BlackjackAction.STAND,
    "4": BlackjackAction.STAND,
    "5": BlackjackAction.STAND,
    "6": BlackjackAction.STAND,
    "7": BlackjackAction.STAND,
    "8": BlackjackAction.STAND,
    "9": BlackjackAction.STAND,
    "T": BlackjackAction.STAND,
    "A": BlackjackAction.STAND,
  },
  // Soft hands A2-A9
  A2: {
    "2": BlackjackAction.HIT,
    "3": BlackjackAction.HIT,
    "4": BlackjackAction.HIT,
    "5": BlackjackAction.DOUBLE,
    "6": BlackjackAction.DOUBLE,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    T: BlackjackAction.HIT,
    A: BlackjackAction.HIT,
  },
  A3: {
    "2": BlackjackAction.HIT,
    "3": BlackjackAction.HIT,
    "4": BlackjackAction.HIT,
    "5": BlackjackAction.DOUBLE,
    "6": BlackjackAction.DOUBLE,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    T: BlackjackAction.HIT,
    A: BlackjackAction.HIT,
  },
  A4: {
    "2": BlackjackAction.HIT,
    "3": BlackjackAction.HIT,
    "4": BlackjackAction.DOUBLE,
    "5": BlackjackAction.DOUBLE,
    "6": BlackjackAction.DOUBLE,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    T: BlackjackAction.HIT,
    A: BlackjackAction.HIT,
  },
  A5: {
    "2": BlackjackAction.HIT,
    "3": BlackjackAction.HIT,
    "4": BlackjackAction.DOUBLE,
    "5": BlackjackAction.DOUBLE,
    "6": BlackjackAction.DOUBLE,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    T: BlackjackAction.HIT,
    A: BlackjackAction.HIT,
  },
  A6: {
    "2": BlackjackAction.HIT,
    "3": BlackjackAction.DOUBLE,
    "4": BlackjackAction.DOUBLE,
    "5": BlackjackAction.DOUBLE,
    "6": BlackjackAction.DOUBLE,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    T: BlackjackAction.HIT,
    A: BlackjackAction.HIT,
  },
  A7: {
    "2": BlackjackAction.STAND,
    "3": BlackjackAction.DOUBLE,
    "4": BlackjackAction.DOUBLE,
    "5": BlackjackAction.DOUBLE,
    "6": BlackjackAction.DOUBLE,
    "7": BlackjackAction.STAND,
    "8": BlackjackAction.STAND,
    "9": BlackjackAction.HIT,
    T: BlackjackAction.HIT,
    A: BlackjackAction.HIT,
  },
  A8: {
    "2": BlackjackAction.STAND,
    "3": BlackjackAction.STAND,
    "4": BlackjackAction.STAND,
    "5": BlackjackAction.STAND,
    "6": BlackjackAction.STAND,
    "7": BlackjackAction.STAND,
    "8": BlackjackAction.STAND,
    "9": BlackjackAction.STAND,
    T: BlackjackAction.STAND,
    A: BlackjackAction.STAND,
  },
  A9: {
    "2": BlackjackAction.STAND,
    "3": BlackjackAction.STAND,
    "4": BlackjackAction.STAND,
    "5": BlackjackAction.STAND,
    "6": BlackjackAction.STAND,
    "7": BlackjackAction.STAND,
    "8": BlackjackAction.STAND,
    "9": BlackjackAction.STAND,
    T: BlackjackAction.STAND,
    A: BlackjackAction.STAND,
  },
  "22": {
    "2": BlackjackAction.HIT,
    "3": BlackjackAction.HIT,
    "4": BlackjackAction.HIT,
    "5": BlackjackAction.HIT,
    "6": BlackjackAction.HIT,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    T: BlackjackAction.HIT,
    A: BlackjackAction.HIT,
  },
  "33": {
    "2": BlackjackAction.HIT,
    "3": BlackjackAction.HIT,
    "4": BlackjackAction.HIT,
    "5": BlackjackAction.HIT,
    "6": BlackjackAction.HIT,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    T: BlackjackAction.HIT,
    A: BlackjackAction.HIT,
  },
  "44": {
    "2": BlackjackAction.HIT,
    "3": BlackjackAction.HIT,
    "4": BlackjackAction.HIT,
    "5": BlackjackAction.HIT,
    "6": BlackjackAction.HIT,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    T: BlackjackAction.HIT,
    A: BlackjackAction.HIT,
  },
  "55": {
    "2": BlackjackAction.DOUBLE,
    "3": BlackjackAction.DOUBLE,
    "4": BlackjackAction.DOUBLE,
    "5": BlackjackAction.DOUBLE,
    "6": BlackjackAction.DOUBLE,
    "7": BlackjackAction.DOUBLE,
    "8": BlackjackAction.DOUBLE,
    "9": BlackjackAction.DOUBLE,
    T: BlackjackAction.HIT,
    A: BlackjackAction.HIT,
  },
  "66": {
    "2": BlackjackAction.HIT,
    "3": BlackjackAction.HIT,
    "4": BlackjackAction.STAND,
    "5": BlackjackAction.STAND,
    "6": BlackjackAction.STAND,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    T: BlackjackAction.HIT,
    A: BlackjackAction.HIT,
  },
  "77": {
    "2": BlackjackAction.STAND,
    "3": BlackjackAction.STAND,
    "4": BlackjackAction.STAND,
    "5": BlackjackAction.STAND,
    "6": BlackjackAction.STAND,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    T: BlackjackAction.HIT,
    A: BlackjackAction.HIT,
  },
  "88": {
    "2": BlackjackAction.STAND,
    "3": BlackjackAction.STAND,
    "4": BlackjackAction.STAND,
    "5": BlackjackAction.STAND,
    "6": BlackjackAction.STAND,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    T: BlackjackAction.HIT,
    A: BlackjackAction.HIT,
  },
  "99": {
    "2": BlackjackAction.STAND,
    "3": BlackjackAction.STAND,
    "4": BlackjackAction.STAND,
    "5": BlackjackAction.STAND,
    "6": BlackjackAction.STAND,
    "7": BlackjackAction.STAND,
    "8": BlackjackAction.STAND,
    "9": BlackjackAction.STAND,
    T: BlackjackAction.STAND,
    A: BlackjackAction.STAND,
  },
  TT: {
    "2": BlackjackAction.STAND,
    "3": BlackjackAction.STAND,
    "4": BlackjackAction.STAND,
    "5": BlackjackAction.STAND,
    "6": BlackjackAction.STAND,
    "7": BlackjackAction.STAND,
    "8": BlackjackAction.STAND,
    "9": BlackjackAction.STAND,
    T: BlackjackAction.STAND,
    A: BlackjackAction.STAND,
  },
  AA: {
    "2": BlackjackAction.HIT,
    "3": BlackjackAction.HIT,
    "4": BlackjackAction.STAND,
    "5": BlackjackAction.STAND,
    "6": BlackjackAction.STAND,
    "7": BlackjackAction.HIT,
    "8": BlackjackAction.HIT,
    "9": BlackjackAction.HIT,
    T: BlackjackAction.HIT,
    A: BlackjackAction.HIT,
  },
};

export const bestAction = (phc: string, dhc: string) => {
    console.log(phc, dhc);
    return actionMap[phc][dhc];
}